### ISSUE TITLE
Unable to use the 64 bit SDK library iowkit.dll

### ISSUE THREAD

**Issue by virtual-maker** [Tederean/FastIOW#2]
Hello Tederean,

great work your library and thanks a lot for sharing it here. It helps me perfect to getting started with my new IO-Warrior56 Dongle see: [USB to I2C and SPI](https://www.codemercs.com/en/dongles/iow56dg)

I played around with your lib and found an issue with use of the 64 bit SDK library iowkit.dll.
Problem is the handle datatype int in NativeLib.cs which is 32bit but the x64 handles are 64bit.
So the half of the handle number is cut off and becomes useless.

In my fork of your project I have fixed the native handle data type to IntPtr which is to use for handles in C#. Also when the original library datatype is uint then it should not be silently changed to int.

Furthermore most example project settings had wrong RootNamespace and AssemblyName.
This I have also fixed.

I have created a pull request with these fixes: #1

BR Immo

**Comment by Tederean** [comment]
Hi virtual-maker,

glad to see that this project can help someone. I've merged your pull request, excellent work!

I've accidently used the 32bit iowkit.dll all the time, in expectation it is 64bit... Good that someone else tested it :+1: I updated also the installation manual, should hopefully work now without issues.
