### ISSUE TITLE
Add example for PCA9555 I2C port expander

### ISSUE THREAD

**Issue by virtual-maker** [Tederean/FastIOW#4]
Hi Tederean,

I have create an additional I2C example with PCA9555 IO port expander chip to measure maximum blink frequency. I got very good result with 166.6 Hz on my Win10 PC. 

I have compared this with your existing Blink example with direct output to IO pin which has max speed of 250 Hz. So I have added a comment to your Blink example for speed test.

I have created a pull request with these additions: #3 
BR Immo

**Comment by Tederean** [comment]
We're happy to add that. :+1:
